config/routes.rb
Rails.application.routes.draw do
  get 'pictures/new'
  get 'pictures/create'
  get 'pictures/update'
  get 'pictures/destroy'
  root 'users#index'
  
  get '/signup', to: 'users#new'
  get '/signup/new', to: 'users#new'
  post '/signup/new', to: 'users#create'

  get '/sessions/:id', to: 'sessions#new'
  get '/destroy', to: 'sessions#destroy'
  post 'sessions/create', to: 'sessions#create'
  resources :sessions

  get '/pictures/new', to: 'pictures#new'
  get '/pictures', to: 'pictures#index'
  post '/pictures/create', to: 'pictures#create'
  resources :pictures

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/picture.rb
class Picture < ApplicationRecord
  has_many_attached :images
  validates_presence_of :name
  validates_length_of :name, :minimum => 1

end

app/models/rename_column.rb
class RenameColumn < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # has_many :pictures
  has_secure_password
  validates_presence_of :fname, :lname, :email, :password
  validates_uniqueness_of :email
  validates_length_of :password, :minimum => 5
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  def new
  end

  def create
    picture = Picture.create(picture_params)
    if picture.save
      redirect_to pictures_path
    else
      render 'new'
    end
  end

  def index
    @user = User.find_by(id: session[:user_id])
    @post = Picture.all
  end

  def update
  end

  def destroy
  end

  private

  def picture_params
    params.require(:picture).permit(:name, user_id: session[:user_id], files: [])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    # byebug
    @user = User.find_by(id: session[:user_id])
  end

  def create
    # byebug
    @user = User.find_by(email: params[:user][:email])
    if @user && @user.authenticate(params[:user][:password])
      session[:user_id] = @user.id
      flash[:success] = "You have successfully logged in"
      redirect_to "/sessions/#{@user.id}"
    else
      flash.now[:error] = "There was something wrong with your login information"
      render '/users/index'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You have successfully logged out"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  end

  def create
    # byebug
    user = User.create(user_params)
    session[:user_id] = user.id
    if user.save
      redirect_to "/sessions/#{user.id}"
    else
      flash.now[:error] = "Something wrong with details provided!"
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:fname, :lname, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash_message.html.erb
   <% flash.each do |type, msg| %>
      <div class="alert alert-info">
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= msg %>
      </div>
    <% end %>

app/views/layouts/_navigation.html.erb
<nav class='navbar navbar-light bg-primary'>
  <div>
    <% if session[:user_id] %>
      <a href="/pictures" class="badge text-white"><h2>Instagram</h2></a>
    <% end %>
  </div>

  <div>
    <% if session[:user_id] %>
      <a href='/destroy' class='btn btn-success btn-sm' role='button'>Log Out</a>
    <% else %>
      <a href='/signup' class='btn btn-success btn-sm' role='button'>Sign Up</a>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instagram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <title>Instagram</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

    <%= render 'layouts/navigation'%>
    <%= render 'layouts/flash_message'%>
  
    <div class='container my-3'>
      <%= yield %>
    </div>

</html>

app/views/pictures/create.html.erb
<h1>Pictures#create</h1>
<p>Find me in app/views/pictures/create.html.erb</p>

app/views/pictures/destroy.html.erb
<h1>Pictures#destroy</h1>
<p>Find me in app/views/pictures/destroy.html.erb</p>

app/views/pictures/index.html.erb
<% if session[:user_id] %>
  <p>Welcome <%= @user.fname %> <%= @user.lname %></p>

<% end %>

<%= link_to 'Post', pictures_new_path, class: 'btn btn-success btn-sm' %></br>

<% @post.each do |post| %>
  <%= post.name %></br>

<% end %>

app/views/pictures/new.html.erb
<h1>Make a new post</h1>

<%= form_for :picture, :url => {:controller => 'pictures', :action => 'create'} do |form| %>

  <%= form.text_field :name, placeholder: 'Description' %></br>
  <%= form.file_field :images, multiple: true %></br>

  <%= form.submit 'Post' %>

<% end %>

app/views/pictures/update.html.erb
<h1>Pictures#update</h1>
<p>Find me in app/views/pictures/update.html.erb</p>

app/views/users/index.html.erb
<h1>Welcome To Instagram</h1>

<%= form_for :user, :url => {:controller => 'sessions', :action => 'create'} do |form| %>

  <%= form.text_field :email, placeholder: 'email' %> <br />
  <%= form.password_field :password, placeholder: 'Password' %> <br />

  <%= form.submit "Sign In" %>

<% end %>

<h3>Don't have an account?</h3>
<%= link_to 'Sign Up', signup_path, id: 'sign-up' %>

app/views/users/log_in.html.erb
<h1>Log In</h1>


<h3>Don't have an account?</h3>
<%= link_to 'Sign Up', signup_path %>

app/views/users/new.html.erb
<h1>Create Account</h1>

<%= form_for :user, :url => {:controller => 'users', :action => 'create'} do |f| %>

  <%= f.text_field :fname, placeholder: 'First Name' %> <br />
  <%= f.text_field :lname, placeholder: 'Last Name' %> <br />
  <%= f.text_field :email, placeholder: 'email' %> <br />
  <%= f.password_field :password, placeholder: 'Password' %> <br />

  <%= f.submit "Create Account" %>

<% end %>

app/views/users/sign_up.html.erb
<h1>Create Account</h1>

<%= form_for :user, :url => {:controller => 'users', :action => 'create'} do |f| %>

  <%= f.label :fname %>
  <%= f.text_field :fname %> <br />

  <%= f.label :lname %>
  <%= f.text_field :lname %> <br />

  <%= f.label :email %>
  <%= f.text_field :email %> <br />

  <%= f.label :password %>
  <%= f.password_field :password %> <br />

  <%= f.submit "Create Account" %>

<% end %>